/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface EncodeOptions {
  /** bytes of an external keys table */
  globalKeysTableBytes?: Buffer
  /** compression level for zstandard. 1-22. Default is 3. */
  compressionLevel?: number
  /** pre trained zstandard dictionary */
  zstdDict?: Buffer
}
export interface DecodeOptions {
  /** bytes of an external keys table */
  globalKeysTableBytes?: Buffer
  /** pre trained zstandard dictionary */
  zstdDict?: Buffer
}
/** Encode a JSON object (object, array, string, number, boolean, null) to a Buffer */
export function encode(value: any, encodeOptions?: EncodeOptions | undefined | null): Buffer
/** Decode a Buffer to a JSON object (object, array, string, number, boolean, null). */
export function decode(fracJsonBytes: Buffer, decodeOptions?: DecodeOptions | undefined | null): any
/**
 * Generate a keys table from a list of unique keys.
 * To improve performance during encoding, keys should be sorted by frequency of occurrence.
 */
export function keysTableFromKeys(keys: Array<string>): Buffer
/** Generate a keys table from a JSON object. */
export function keysTableFromJson(obj: any, maxCount?: number | undefined | null, occurrenceCutoff?: number | undefined | null): Buffer
