/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function encode(value: any, globalKeysTableBytes?: Buffer | undefined | null, compressionLevel?: number | undefined | null): Buffer
export function decode(fracJsonBytes: Buffer, globalKeysTableBytes?: Buffer | undefined | null): any
export function keysTableFromKeys(keys: Array<string>): Buffer
export function keysTableFromJson(obj: any, maxCount?: number | undefined | null, occurrenceCutoff?: number | undefined | null): Buffer
