/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function encodeFracJson(value: any, globalKeysTableBytes?: Buffer | undefined | null, compressionLevel?: number | undefined | null): Buffer
export function decodeFracJson(fracJsonBytes: Buffer, globalKeysTableBytes?: Buffer | undefined | null): any
