name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: ${{ false }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu

    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          frac_json_rust/.cargo-cache
          frac_json_rust/target/
        key: x86_64-unknown-linux-gnu-cargo-ubuntu-latest

    - name: Build
      run: cargo build --verbose
      working-directory: frac_json_rust/frac_json

    - name: Test
      run: cargo test --verbose
      working-directory: frac_json_rust/frac_json
